In [1]:
'''
import random
a = [1,1,1,6,1,1,4,4,3,2,0,10,5]
from itertools import groupby
k = [len(list(group)) for key, group in groupby(a)]

m = [k for x in range(len(k))]
s=groupby(a)
s
k

count=0
for i in range(len(a)):
    for j in range(len(a)):
        if a[i] == a[j]:
            count+=1
            #a[i]=count
            x = [[count for i in range(len(k))] for j in range(len(k))]
            print(count)

print(len(x))
x

from math import sqrt
from random import random
A = [[1,1,1,6,2,1,5,4,3,2,0,10,5]]
b = [random() for i in range(len(A))]
tmp = [0] * len(A)

for iteration in range(10000):

        for i in range(0, len(A)):
            tmp[i] = 0
            for j in range(0, len(A)):
                tmp[i] += A[i][j] * b[j]

        normSq = 0
        for k in range(0, len(A)):
            normSq += tmp[k] * tmp[k]
        norm = sqrt(normSq)

        for i in range(len(A)):
            b[i] = tmp[i] / norm
print(b)

import random

powerIteration(a)
for i, j in enumerate(a[:-1]):
    if j  == a[i+1]: 
        a[i] = "foo" 
        a[i+1] = "foo"
print(a)

for x in range(len(a)):
    row = []
    for y in range(len(a)):
        row.append(0)
    a.append(row)
a
'''

'\nimport random\na = [1,1,1,6,1,1,4,4,3,2,0,10,5]\nfrom itertools import groupby\nk = [len(list(group)) for key, group in groupby(a)]\n\nm = [k for x in range(len(k))]\ns=groupby(a)\ns\nk\n\ncount=0\nfor i in range(len(a)):\n    for j in range(len(a)):\n        if a[i] == a[j]:\n            count+=1\n            #a[i]=count\n            x = [[count for i in range(len(k))] for j in range(len(k))]\n            print(count)\n\nprint(len(x))\nx\n\nfrom math import sqrt\nfrom random import random\nA = [[1,1,1,6,2,1,5,4,3,2,0,10,5]]\nb = [random() for i in range(len(A))]\ntmp = [0] * len(A)\n\nfor iteration in range(10000):\n\n        for i in range(0, len(A)):\n            tmp[i] = 0\n            for j in range(0, len(A)):\n                tmp[i] += A[i][j] * b[j]\n\n        normSq = 0\n        for k in range(0, len(A)):\n            normSq += tmp[k] * tmp[k]\n        norm = sqrt(normSq)\n\n        for i in range(len(A)):\n            b[i] = tmp[i] / norm\nprint(b)\n\nimport random\n\npowe

In [24]:
'''
import numpy as np
G = [[2,3],[2,3]]
G = np.array(G)
epsilon = 0.0001

def compute(G):
   
        "G is N*N matrix where if j links to i then G[i][j]==1, else G[i][j]==0"
        N = len(G)
        d = np.zeros(N)
        for i in range(N):
            for j in range(N):
                if (G[j, i] == 1):
                    d[i] += 1
 
        r0 = np.zeros(N, dtype=np.float32) + 1.0 / N
        # construct stochastic M
        M = np.zeros((N, N), dtype=np.float32)
        for i in range(N):
            for j in range(N):
                if G[j, i] == 1:
                    M[j, i] = 1.0 / d[i]
        while True:
            r1 = np.dot(M, r0)
            dist = self.distance(r1, r0)
            if dist < self.epsilon:
                break
            else:
                r0 = r1
 
        return r1

def __init__(self, beta=0.85, epsilon=0.0001):
        self.epsilon = epsilon
def distance(self, v1, v2):
        v = v1 - v2
        v = v * v
        np.sum(v)
compute(G)
'''
'''
c=0
N = len(unique_list)
d = np.zeros(N)
for i in range(len(arraymat)):
    for j in range(N):
        #print("sf")
        d[i]+=1
arraymat

r0 = np.zeros(N, dtype=np.int32) + 1.0 / N
ro
G = np.array(unique_list)
print(G)
M

for o,jj in enumerate(count.values()):
    
    Arrayz.append(jj)
'''
    
    '''for il,ll in enumerate(unique_list):
        
        sorted(count.items())
        
        if ll in d:
            print("ll",ll)
        
        else:
            print("pt", pt)
            count[ll]=0

d = np.array(d)
d
            ''' 
'''
dd = []
ap=[]
for c,cia in enumerate(arraymat):
    dd.append(cia[0])
dd.sort()
print(dd)
#count = collections.Counter(dd)
print(count)
for o in count.values():
    ap.append(o)
print(ap)

ddu = [
   e
   for l, e in enumerate(dd)
    if dd.index(e) == l
    ]
print(ddu)
dduu = ddu.sort()
print(dduu)

Arraym = np.zeros((len(unique_list),1), dtype='int32')
print(Arraym)
for u in range(0,len(unique_list)):
    k = unique_list.index(7)
    #print(k)
    Arraym[k] = Arrayz[k] 
    
print("kk",Arraym)

Arrayx = np.array(ap)
Arrayx.reshape((len(Arrayx),1))
print(Arrayx)
k = dd.index(dd[0])
m = dd.index(dd[1])

'''

'\nc=0\nN = len(unique_list)\nd = np.zeros(N)\nfor i in range(len(arraymat)):\n    for j in range(N):\n        #print("sf")\n        d[i]+=1\narraymat\n\nr0 = np.zeros(N, dtype=np.int32) + 1.0 / N\nro\nG = np.array(unique_list)\nprint(G)\nM\n'

In [23]:
#Creating list of list
import numpy as np
i=0
list = [4,5,5,5,8,5,8,8,8,6,7]
unique_list = [
   e
   for l, e in enumerate(list)
    if list.index(e) == l
    ]
f = unique_list.sort()
print("Unique list:",unique_list)
pids=5
listoflist = []
while i<len(list):
    listoflist.append(list[i:i+3])
    i+=3
#print(listoflist)

#Array matrix of list of list
arraymat = np.array(listoflist)
print(arraymat)

#Sqaure Matrix
M = np.zeros((N,N), dtype=np.int32)
print(M)

Unique list: [4, 5, 6, 7, 8]
[[4, 5, 5] [5, 8, 5] [8, 8, 8] [6, 7]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
import collections, numpy
from operator import itemgetter

M = np.zeros((N, N), dtype=np.int32)

d = []
Arraypz = []
pt=[]

for l,dont in enumerate(arraymat):

    for fc in range(0,(len(dont)-1)):
        
        k = unique_list.index(dont[fc])
        m = unique_list.index(dont[fc+1])

        M[k][m]+=1        
        
        for tw in range(fc,(len(dont)-2)):
            
            k = unique_list.index(dont[tw])
            m = unique_list.index(dont[tw+2])

            M[k][m]+=1
        
    d.append(dont[0])
    d.sort()
    count = collections.Counter(d)
   
          
 

Arraypz = np.zeros((N,1), dtype="int32")

for il,ll in enumerate(unique_list):

        if ll in d:
            pk = unique_list.index(ll)
            
            Arraypz[pk]=count.get(ll)
        else:
            pt = unique_list.index(ll)
            
            count[ll]=0
            Arraypz[pt] = 0

#print(count)
print(Arraypz)
print(M)

[[1]
 [1]
 [1]
 [0]
 [1]]
[[0 2 0 0 0]
 [0 2 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 1 0 0 3]]


In [32]:
#Arraypz.reshape((len(Arraypz),1))
FM = np.dot(M,Arraypz)
FM

array([[2],
       [3],
       [0],
       [0],
       [4]])

In [33]:
SM=FM*0.8
SM

array([[ 1.6],
       [ 2.4],
       [ 0. ],
       [ 0. ],
       [ 3.2]])

In [34]:
Final = SM + (Arraypz*0.2)
Final

array([[ 1.8],
       [ 2.6],
       [ 0.2],
       [ 0. ],
       [ 3.4]])

In [35]:
FinalMatrix = (((np.dot(M,Final)*0.8)+(Arraypz*0.2)))
FinalMatrix

array([[  4.36],
       [  7.08],
       [  0.2 ],
       [  0.  ],
       [ 10.44]])