In [20]:
import json
import os.path
import sys
import pickle
from os import listdir
import collections

In [21]:
book1 = open('C:/Users/Rima/Desktop/Rima/Academics/ADM/Project/Dan_CS522/mdp.39015064582888.json/mdp.39015062797538.json', encoding='utf-8')

In [22]:
with book1 as data_file:
    data = json.load(data_file)

In [23]:
print(data['id'])
pages = data['pages'][9]['pid']
print(pages)
print(data['pages'][0]['ner'][0]['text'])

mdp.39015062797538
00000017
Dwight Foster Hamlin


In [24]:
text = ""
count = 0
file = open("to.txt", 'w', encoding='utf-8')
for i, item in enumerate(data['pages']):
    pages = data['pages'][i]['pid']
    #print(pages)
    #print(item)
    count += 1
    for j, field in enumerate(data['pages'][i]['ner']):
        #print(field)
        file.write("  ")
        #print(data['pages'][i]['ner'][j]['text'])
        for k, xylo in enumerate(data['pages'][i]['ner'][j]['text']):
            text = (xylo)   
            file.write(text)
            
#pickle.dump(links, file)
          
file.close()
print(count) 


480


In [25]:
links=[]
f=[]
page = []
file = open("lo.link.txt", 'w', encoding = 'utf-8')
ufile = open("lo.uniquelink.txt", 'w', encoding = 'utf-8')
count = 0
import collections, numpy

for i, item in enumerate(data['pages']):
            #print("Item {0} : {1}".format(i,item))
            wiki = item['wikifier']
            
            page = data['pages'][i]['pid']
            countz = collections.Counter(page)
            #print(len(countz))
            if wiki == []:
                continue
            else:
                for j, field in enumerate(data['pages'][i]['wikifier']):
                    count += 1
                    k = field['link']
                    if k == None:
                        #links = "Chicago school"
                        links.append("Chicago_School")
                        #file.write(data['pages'][i]['pid'] + "%s" % links.append("Chicago_School"))
                        #pickle.load(links)
                        
                        #file.write("\n")
                    else:                        
                        links.append(k)
                        #file.write("%s" % links)
                        c = collections.Counter(links)
                        #with open("lo.lin", 'wb') as f:
                            #pickle.dump(links, f)        
                        #file.write("\n")
                #print(data['pages'][i]['pid'])
                   
#pickle.dump(links,file)
#file.write("\n".join(links))
#links = '\n'.join(links)
listoflist = []
unique_list = [
e
for i, e in enumerate(links)
if links.index(e) == i
]
#unique_list
ufile.write("%s" %(unique_list))
Unique_Links = len(unique_list)
                    #Unique_Links
counter=0   
s=0
ll = []
pages = data["pages"]
for j, page in enumerate(pages):
    wikiR = page["wikifier"]
    lst = []
    for link in wikiR:
        
        lst.append(link['link']) 
        if link['link'] == None:
            lst.remove(None)
        
    if len(lst) == 0:
            lst.append("Chicago School")    
    ll.append(lst)
        
    
    
print(ll)
file.write("%s" %(links))
#print(links[1])
#print(count)
#print(field)p
#f.close()
file.close()
ufile.close()
len(links)
print(listoflist)

#c = collections.Counter(links)

[['Chicago School'], ['Chicago School'], ['http://en.wikipedia.org/wiki/College', 'http://en.wikipedia.org/wiki/Editing', 'http://en.wikipedia.org/wiki/John_Charles_Van_Dyke', 'http://en.wikipedia.org/wiki/Architecture_(magazine)'], ['http://en.wikipedia.org/wiki/College', 'http://en.wikipedia.org/wiki/Editing', 'http://en.wikipedia.org/wiki/John_Charles_Van_Dyke', 'http://en.wikipedia.org/wiki/The_History_of_the_Decline_and_Fall_of_the_Roman_Empire', 'http://en.wikipedia.org/wiki/Rutgers_University', 'http://en.wikipedia.org/wiki/Painting', 'http://en.wikipedia.org/wiki/John_Charles_Van_Dyke', 'http://en.wikipedia.org/wiki/List_of_Doctor_Who_villains', 'http://en.wikipedia.org/wiki/Book_frontispiece', 'http://en.wikipedia.org/wiki/Architecture', 'http://en.wikipedia.org/wiki/Master_of_Arts_(postgraduate)', 'http://en.wikipedia.org/wiki/Architecture', 'http://en.wikipedia.org/wiki/Columbia_College_of_Columbia_University', 'http://en.wikipedia.org/wiki/New_York', 'http://en.wikipedia.or

In [26]:
import numpy as np
arraymat = np.array(ll)
d = []

#print(N)
N = len(unique_list)
print(N)
import collections, numpy
firstC = []
#print(len(arraymat))
M = np.zeros((N, N), dtype=np.int32)
#print(unique_list)
p=0
for l,dont in enumerate(arraymat):
    firstC=arraymat[l]
    #print(dont[l])
    
    #print(dont)
    
    if dont == None:
           dont.remove(None)
    
    
            
    
    for fc in range(0,(len(dont)-1)):
            #print("len(dont)", len(dont))
            #print(fc)      
        k = unique_list.index(dont[fc])
        m = unique_list.index(dont[fc+1])

        M[k][m]+=1
        
        
    
        for tw in range(fc,(len(dont)-2)):
            k = unique_list.index(dont[tw])
            m = unique_list.index(dont[tw+2])

            M[k][m]+=1
        
    d.append(dont[0])
    d.sort()
    count = collections.Counter(d)      
           
    #count = collections.Counter(firstC)
#print(arraymat)
print(d)
M

3135
['Chicago School', 'Chicago School', 'Chicago School', 'Chicago School', 'Chicago School', 'Chicago School', 'Chicago School', 'http://en.wikipedia.org/wiki/2si', 'http://en.wikipedia.org/wiki/Abadie', 'http://en.wikipedia.org/wiki/Abbeville', 'http://en.wikipedia.org/wiki/Acropolis_of_Athens', 'http://en.wikipedia.org/wiki/AdvancED', 'http://en.wikipedia.org/wiki/Africa', 'http://en.wikipedia.org/wiki/Agrigento', 'http://en.wikipedia.org/wiki/Ahmed_I', 'http://en.wikipedia.org/wiki/Amarna', 'http://en.wikipedia.org/wiki/American_Surety_Building', 'http://en.wikipedia.org/wiki/Ancient_Egypt', 'http://en.wikipedia.org/wiki/Ancient_Egypt', 'http://en.wikipedia.org/wiki/Ancient_Egypt', 'http://en.wikipedia.org/wiki/Ancient_Egypt', 'http://en.wikipedia.org/wiki/Ancient_Egypt', 'http://en.wikipedia.org/wiki/Ancient_Egyptian_architecture', 'http://en.wikipedia.org/wiki/Ancient_Egyptian_architecture', 'http://en.wikipedia.org/wiki/Ancient_Greece', 'http://en.wikipedia.org/wiki/Ancient_Ro

array([[ 0,  2,  2, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0, 22,  0],
       [ 0,  0,  0, ...,  0,  0, 24],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [27]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import normalize

M = normalize(M, norm="l1", axis=0)
M

#M_normalized = preprocessing.normalize(M)

C:\Users\Rima\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by the normalize function.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.        ,  1.        ,  0.16666667, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.16666667, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.95652174,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.96      ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [28]:
Arraypz = []
Arraypz = np.zeros((N,1), dtype="int32")

for il,ll in enumerate(unique_list):

        if ll in d:
            pk = unique_list.index(ll)
            #print(pk)
            
            Arraypz[pk]=count.get(ll)
        else:
            pt = unique_list.index(ll)
            count[ll]=0
            Arraypz[pt] = 0

#print(count)
print(Arraypz)
print(M)

#Arraypz.reshape((len(Arraypz),1))
FM = np.dot(M,Arraypz)
FM

[[2]
 [0]
 [0]
 ..., 
 [0]
 [0]
 [0]]
[[ 0.          1.          0.16666667 ...,  0.          0.          0.        ]
 [ 0.          0.          0.16666667 ...,  0.          0.          0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.95652174  0.        ]
 [ 0.          0.          0.         ...,  0.          0.          0.96      ]
 [ 0.          0.          0.         ...,  0.          0.          0.        ]]


array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]])

In [29]:
SM=FM*0.8
SM
Final = SM + (Arraypz*0.2)
Final

array([[ 0.4],
       [ 0. ],
       [ 0. ],
       ..., 
       [ 0. ],
       [ 0. ],
       [ 0. ]])

In [30]:
FinalMatrix = (((np.dot(M,Final)*0.8)+(Arraypz*0.2)))
print(FinalMatrix)
percentile = np.percentile(FinalMatrix, 50)
print(percentile)
implink = []
notimp = []
somelist = []
for i in range(0, len(FinalMatrix)-1):
    if FinalMatrix[i][0] > percentile:
        somelist.append(i)
        
for j, k in enumerate(somelist):
    implink.append(unique_list[k])
print(len(unique_list))
print(len(implink))

for ls, lsk in enumerate(unique_list):
    if lsk not in implink:
        notimp.append(lsk)

[[ 0.4       ]
 [ 0.        ]
 [ 0.00298099]
 ..., 
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
0.036185409431
3135
1567


In [31]:
for l in range(0,100):
    print(implink[l])
print("Not Important")
for l in range(0,100):
    print(notimp[l])

http://en.wikipedia.org/wiki/College
http://en.wikipedia.org/wiki/Book_frontispiece
http://en.wikipedia.org/wiki/Architecture
http://en.wikipedia.org/wiki/New_York
http://en.wikipedia.org/wiki/Diagram
http://en.wikipedia.org/wiki/Sculpture
http://en.wikipedia.org/wiki/Textbook
http://en.wikipedia.org/wiki/Copyright
http://en.wikipedia.org/wiki/Extreme_(band)
http://en.wikipedia.org/wiki/Mr.
http://en.wikipedia.org/wiki/Ancient_Egyptian_architecture
http://en.wikipedia.org/wiki/Iranian_architecture
http://en.wikipedia.org/wiki/Lycian_language
http://en.wikipedia.org/wiki/Jew
http://en.wikipedia.org/wiki/Architecture_of_ancient_Greece
http://en.wikipedia.org/wiki/Roman_architecture
http://en.wikipedia.org/wiki/Church_architecture
http://en.wikipedia.org/wiki/Byzantine_architecture
http://en.wikipedia.org/wiki/Sassanid_Empire
http://en.wikipedia.org/wiki/Mohammedan
http://en.wikipedia.org/wiki/Arabian_Peninsula
http://en.wikipedia.org/wiki/Moors
http://en.wikipedia.org/wiki/Persian_langua

In [49]:
book2 = open('C:/Users/Rima/Desktop/Rima/Academics/ADM/Project/Dan_CS522/mdp.39015064582888.json/mdp.39015062797538.json', encoding='utf-8')
with book2 as data_file:
    dataaa = json.load(data_file)
for i, item in enumerate(dataaa['pages']):
    for j, field in enumerate(dataaa['pages'][i]['wikifier']):
        
        kooo=field['link']
        if kooo in notimp:
            del dataaa['pages'][i]['wikifier'][j]
            #dataaa['pages'][i]['wikifier'][j]['link'] = None
            
with open('updated7538.json', 'w') as data_file:
    dataaa = json.dump(dataaa, data_file)
           

In [33]:
answer = {}
l=[]
ll = open("lo.lin.txt", 'wb')
with open("lo.link.txt", 'rb') as f:
    #for x in f.readlines():
        #print("snf")
        #l = x.decode('utf8').strip()
        
    pickle.dump(links, ll)

In [34]:
Link_Names_File = open("Link_Names.txt", 'w', encoding = 'utf-8')
with open("lo.link.txt", 'r', encoding="utf-8") as f:
    for x in f.readlines():
        onlyWords = x.rsplit('/', 1)[-1]
        Link_Names_File.write(onlyWords)