In [2]:
import os,json,csv,collections
dict={}
os.chdir("F:/ADM/bookjson2")
allfiles_list=[]
for f in os.listdir():
    print(f)
    
    with open(f, encoding="utf-8") as json_file:#print(json_file)
        lists=[]
        allfiles_list.append
        a=json.load(json_file)
        for each_page in  a['pages']:
                for each_pid in each_page['wikifier']:
                        lists.append(each_pid['link'])
    dict[f]=lists
print(dict)

1905_uiug.30112078740336.json
1907_mdp.39015062797538.json
1909_uva.x001197927.json
1919_uc1.b3819355.json
{'1905_uiug.30112078740336.json': ['http://en.wikipedia.org/wiki/Illinois', 'http://en.wikipedia.org/wiki/United_States', 'http://en.wikipedia.org/wiki/Painting', 'http://en.wikipedia.org/wiki/Ronnie_DeVoe', 'http://en.wikipedia.org/wiki/Europe', 'http://en.wikipedia.org/wiki/Tiffany_&_Co.', 'http://en.wikipedia.org/wiki/Diamond', 'http://en.wikipedia.org/wiki/Gemstone', 'http://en.wikipedia.org/wiki/Engagement_ring', 'http://en.wikipedia.org/wiki/Engraving', 'http://en.wikipedia.org/wiki/Gold', 'http://en.wikipedia.org/wiki/Wedding_ring', 'http://en.wikipedia.org/wiki/Engraving', 'http://en.wikipedia.org/wiki/Marriage', 'http://en.wikipedia.org/wiki/Sampling_(music)', 'http://en.wikipedia.org/wiki/Tiffany_&_Co.', 'http://en.wikipedia.org/wiki/United_States', 'http://en.wikipedia.org/wiki/Tiffany_&_Co.', 'http://en.wikipedia.org/wiki/Tiffany_&_Co.', 'http://en.wikipedia.org/wiki/T

In [91]:
# matrix generation
list2=[]
x=list(dict.keys())
for i in range(0,len(x)):
    list1=[]
    for j in range(0,len(x)):
        a=set(list(dict[x[i]]))
        b=set(list(dict[x[j]]))
        c=a.intersection(b)
        list1.append(len(c))
    list2.append(list1)
        
print(list2)      
    
    
        
        

[[820, 120, 114, 228], [120, 3135, 3006, 300], [114, 3006, 3131, 302], [228, 300, 302, 2450]]


In [95]:
vector=[]
for i in range(len(x)):
    vector.append(1)
vector=np.array(vector)
vector=np.transpose(vector)
vector_unit=vector
print(vector_unit)
matrix=np.array(list2)


prev_vector=vector*.5
count=0
while  count in range(3) :
    prev_vector=vector
    vector=(np.dot(vector,matrix) * .85)+ ((vector_unit*0.15)/len(x))
    count +=1
    print(vector,prev_vector)
    
         
print(vector)       

[1 1 1 1]
[ 1089.7375  5576.8875  5570.0875  2788.0375] [1 1 1 1]
[  2408452.74625   29915244.361875  29894742.446875   8869227.0325  ] [ 1089.7375  5576.8875  5570.0875  2788.0375]
[  9.34570323e+09   1.58608019e+11   1.58506923e+11   3.42392911e+10] [  2408452.74625   29915244.361875  29894742.446875   8869227.0325  ]
[  9.34570323e+09   1.58608019e+11   1.58506923e+11   3.42392911e+10]


In [ ]:
if (np.array_equal(vector,vector)) is "True":
    print("cja")
print(np.array_equal(vector,vector))
t="a"
if t is "a":
    print(5)

In [79]:
vector=[[1],[1],[1],[1]]
np.transpose(vector)


array([[1, 1, 1, 1]])

In [56]:
import numpy as np
a=[1,1]
b=[1,1]
c=0.85
d=0.15
e=np.array_equal(a,b)
if e is  True:
    print("fdkfkd")



fdkfkd


In [99]:
x=[[820, 120, 114, 228], [120, 3135, 3006, 300], [114, 3006, 3131, 302], [228, 300, 302, 2450]]
y=[1,1,1,1]
y=(np.dot(x,y)*0.85)+ (vector_unit*0.15/4)


bac



array([ 1089.7375,  5576.8875,  5570.0875,  2788.0375])

In [100]:

y=(np.dot(x,y)*0.85)+ (vector_unit*0.15/4)
y

array([  2408452.74625   ,  29915244.36187501,  29894742.446875  ,
         8869227.0325    ])